# MkDocs config options

# Meta
site_name: 'WildBeast Documentation'
site_description: 'Welcome to the WB documentation'
site_author: 'TheSharks'

# Sitemap
pages:
  - Home: 'index.md'
  - Command reference: 'commands.md'
  - Windows Guide: 'install_windows.md'
  - Linux Guide: 'install_linux.md'
  - Docker Guide: 'install_docker.md'
  - Updating: 'updating.md'
  - FAQ: 'faq.md'
  - Custom Command Framework: 'custom_commands.md'
  - Gateway Sharding System: 'sharding.md'

# Theme
theme: 'material'

# Material config options

# Repo
repo_name: 'GitHub'
repo_url: 'https://github.com/TheSharks/WildBeast'

# Copyright
copyright: 'Copyright Â© 2016 TheSharks, "Discord", "Discord App", and any associated logos are registered trademarks of Hammer & Chisel, inc.'

# Extra options
extra:
  logo: 'img/wb-head-circle.png'
  palette:
    primary: 'indigo'
    accent: 'blue'
  font:
    text: 'Droid Sans'
    font: 'Droid Sans Mono'
  author:
    github: 'TheSharks'
    twitter: 'Dougley35'
